<?php

namespace MembershipBundle\Repository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}
