membership:
    resource: "@MembershipBundle/Resources/config/routing.yml"
    prefix:   /membership

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

club:
    resource: "@ClubBundle/Resources/config/routing.yml"
    prefix:   /club

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"