ads_index:
    path:     /
    defaults: { _controller: "MembershipBundle:Ads:index" }
    methods:  GET

ads_show:
    path:     /{id}/show
    defaults: { _controller: "MembershipBundle:Ads:show" }
    methods:  GET

ads_new:
    path:     /new
    defaults: { _controller: "MembershipBundle:Ads:new" }
    methods:  [GET, POST]

ads_edit:
    path:     /{id}/edit
    defaults: { _controller: "MembershipBundle:Ads:edit" }
    methods:  [GET, POST]

ads_delete:
    path:     /{id}/delete
    defaults: { _controller: "MembershipBundle:Ads:delete" }
    methods:  DELETE
