# config/validator/validation.yaml
MembershipBundle\Entity\Ads:
  properties:
    name:
      - Regex:
          pattern: '/^[a-z]+$/i'
          htmlPattern: '^[a-zA-Z]+$'
    description:
      - Regex:
          pattern: '/^[a-z]+$/i'
          htmlPattern: '^[a-zA-Z]+$'
MembershipBundle\Entity\Plan:
  properties:
    name:
      - Regex:
          pattern: '/^[a-z]+$/i'
          htmlPattern: '^[a-zA-Z]+$'
      - NotBlank: ~
    price:
      - Regex:
          pattern: '/^[0-9]+$/i'
          htmlPattern: '^[0-9]+$'
      - NotBlank: ~
    quota:
      - Regex:
          pattern: '/^[0-9]+$/i'
          htmlPattern: '^[0-9]+$'
      - NotBlank: ~